(defun ciclos-por-tiempo (minutos)
	(let ((ciclos-completos (truncate (/ (* minutos 60) 216))))
		(format nil "Numero de ciclos completados ~a" ciclos-completos)
	)
)

(defun informe-dis-tem (tiempo-total)
  (let ((calculo-rojo (truncate (* tiempo-total (/ 90 216))))
        (calculo-amarillo (truncate (* tiempo-total (/ 6 216))))
        (calculo-verde (truncate (* tiempo-total (/ 120 216)))))
    (format nil "rojo: ~a segundos  amarillo: ~a segundos  verde: ~a segundos" calculo-rojo calculo-amarillo calculo-verde)
  )
)